backends:
  brew:
    list: 'brew list'
    upgrade: 'brew upgrade'
    install: 'brew install'

pkgdbs: 'packages'

symlinks:
  - to: 'b.txt'
    from: 'a.txt'
  - to: 'dir/b.txt'
    from: 'a.txt'

tasks:
  # This will install brew and all packages
  - punkt: brew
