env:
  - DEP_VERSION=0.3.2

sudo: required

language: go

go:
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - dep ensure -no-vendor -dry-run
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
