language: go

go:
  - 1.9
  - tip

install: true

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false

before_install:
  - pip3 install pipenv

before_script:
  - (cd tests; pipenv install --three)
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

script:
  - (cd tests; pipenv run python)
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)
