backends:
  brew: 'backends/brew.yaml'
  yarn: 'backends/yarn.yaml'

package_files: 'packages'

symlinks:
  'b.txt': 'a.txt'
  'dir/b.txt': 'a.txt'

tasks:
  # This will install brew and all packages
  - goot: brew
  - shell: yarn config set repository 'artifactory.maxm.se:4873'
  - goot: yarn
  - shell: echo 'hello'
