---
- hosts: all
  connection: local

  vars_files:
    - vars/punkt.yml
    - vars/homebrew.yml
    - vars/symlinks.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: symlink
      tags: ['symlink']

  tasks:
    - include_tasks: tasks/ansible-setup.yml
    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
