---
- hosts: all
  connection: local

  vars_files:
    - vars/punkt.yml
    - vars/homebrew.yml
    - vars/symlinks.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: symlink
      tags: ['symlink']

  pre_tasks:
    - name: Include user configuration
      include_vars:
        dir: "{{ punkt_config_home }}/vars"
        extensions: ['yml', 'yaml', 'json']
        files_matching: '.(yml|yaml|json)'

  tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: "{{ item }}"
      with_fileglob: "{{ punkt_config_home }}/tasks/*.yml"
